### ISSUE TITLE
Ganache-like testing feature

### ISSUE THREAD

**Issue by HyunggyuJang** [inkdevhub/swanky-node#49]
# Overview (What and Why)
Ganache (https://trufflesuite.com/ganache/) or Hardhat network helpers (https://hardhat.org/hardhat-network-helpers/docs/reference) is a infrastructure that implements a node for EVM with extra features for local tests, to name a few:
- block time stamp manipulation (can mine a block with arbitrary block time stamp)
- block number manipulation
- taking a snapshot and retrieve later
- Balance manipulation of accounts
- Impersonate any account

It will accelerate the development of dapps using ink! if we have such nice testing node implementation.
# How

- [ ]  Port the implementations of testing node to swanky node
  + Hardhat network implementation: https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/hardhat-network/provider/HardhatBlockchain.ts
  + Foundry (rust implementation): https://github.com/foundry-rs/foundry/blob/master/anvil/core/src/eth/block.rs
- [ ]  Connect underlying node interaction from swanky-cli facade
- [ ] Expose the node manipulation api of swanky-cli as a node package

# Definition of Done

- [ ]  Unit test cases for each node manipulation features

**Comment by codespool** [comment]
Adding to project for discussion in next sprint planning.

**Comment by shunsukew** [comment]
@HyunggyuJang 
Thank you for the suggestion

> block time stamp manipulation (can mine a block with arbitrary block time stamp)
In swanky-node, you can manually mine blocks by RPC call `engine_createBlock` and `engine_finalizeBlock`. 
Block number does matter, I think blocks don't need to be mined at exact timestamp user specified. (Ganache, Hardhat doesn't have such feature afaik).
Or did you mean having a option to specify blocktime (replacement of instant seal, blocktime = 0)?

> block number manipulation
We have RPC call as mentioned before, it's possible to forward blocks to the number user specified in swanky-cli side. Similar to https://hardhat.org/hardhat-network-helpers/docs/reference#mineupto(blocknumber). 


> taking a snapshot and retrieve later
This would be nice alongside with import feature.

> Balance manipulation of accounts
This will come soon.

> Impersonate any account
To allow operations on accounts whose private key you don't have? This need Substrate level modification, might take time.
https://trufflesuite.com/blog/introducing-ganache-7/#7-impersonate-any-account
From my point of view, If swanky-node cannot import mainnet (e.g. Astar) states, because runtime logic and storage are different, this feature has low value to add. Need investigation.

**Comment by shunsukew** [comment]
As for block manipuration,
In Europe (old Substrate local dev node developed by Patract lab), there's a feature called `europa_forwardToHeight` and `europa_backwardToHeight`.
Currently swanky-node only support 1 block creation RPC, but forwarding blocks number feature (it could be just an option in engine_createBlock or separate RPC) would be useful.
And, substrate natively support `revert` subcommand, but reverting RPC feature like Europe has is also good to have.

<img width="803" alt="Screen Shot 2023-05-10 at 14 58 26" src="https://github.com/AstarNetwork/swanky-node/assets/28953860/b091541b-6d5f-4c57-9a90-00c609e4e807">

**Comment by shunsukew** [comment]
> taking a snapshot and retrieve later
As for snapshotting, you can choose which path to store blockchain data by specifying `--db-path` option. Then later you can choose which db path to use.
So, without compression feature, there's no additional value in my opinion.

**Comment by HyunggyuJang** [comment]
@shunsukew Thanks for your sincere answer and sorry for being late to response. 

> Block number does matter, I think blocks don't need to be mined at exact timestamp user specified. (Ganache, Hardhat doesn't have such feature afaik).
Or did you mean having a option to specify blocktime (replacement of instant seal, blocktime = 0)?

What I meant was https://hardhat.org/hardhat-network-helpers/docs/reference#increase(amountinseconds). If it were you are indicating, then yes!

> some option to create multiple blocks at one single call

Yes, that would be great, but as you pointed instant seal will work also if not trying to proceed tremendous number of blocks to lag the execution of tests.

> From my point of view, If swanky-node cannot import mainnet (e.g. Astar) states, because runtime logic and storage are different, this feature has low value to add. Need investigation.

Agree, but it also helpful to test contracts which using deterministic addresses.
